### PR TITLE
new

### PR DESCRIPTION
**Pull request by sylviama**

### CODE REVIEW

**Comment by sylviama** [comment]
Hi, I just updated my javascript quiz. I did it wrong before because I didn't console log the result but print in html with using CSS. The new try is exactly follow the instruction. Let me know.

Thanks,

**Comment by gregkorte** [comment]
Hey Sylvia. Getting closer on your quiz. A few things. First, your program should handle the `Enter` keypress as well as the button. Second, and I didn't notice this the first time through. The input for the tree height should be a text input. Third, on your button you're calling a function. What we would rather see is a separation between the html and the javascript. Take another look and ping me in slack when you are finished.

**Comment by sylviama** [comment]
Hi, Greg, I just (1)added a form tag so that it could automatically doing enter and click; (2)I changed the input type into "text" (3)I use an addEventHandler in javascript instead of onclick in html.

Let me know what you think. Thanks,

**Comment by gregkorte** [comment]
Hey Sylvia. Your quiz looks good. Creative and concise solution. Well done! :+1:

**Pull request merged**
